### PR TITLE
fix(node-modules-polyfill): replace `rollup-plugin-node-polyfills` with `rollup-plugin-polyfill-node`

### LINKED ISSUE #18: [node-modules-polyfill] Replace unmaintained `rollup-plugin-node-polyfills` dependency
Same reasoning as in https://github.com/ionic-team/rollup-plugin-node-polyfills/pull/32.

Since that repo is never touched in the last 3 years, it's probably a good idea to either look at the community forks (see https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/28) _or_ create our own fork.
I would prefer to use @FredKSchott [fork](https://github.com/FredKSchott/rollup-plugin-polyfill-node) as he's the creator of `snowpack` & that's the one used by the `snowpack` library too, so it probably has the most up to date version of the `rollup-plugin-node-polyfills` lib.

Edit: @FredKSchott's fork is also recommended by the @rollup team: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Re-submission of #19

This still has the same problem as @connorjclark pointed out in https://github.com/remorses/esbuild-plugins/pull/19#discussion_r990506227 (see also #28 for the bug issue)

> Cannot read directory "\x00polyfill-node._stream_duplex": invalid argument

@remorses @connorjclark If you have any idea what the problem is & can point me into the right direction, I'm happy to update this PR

Maybe the problem is even deeper & we should look at @FredKSchott's `rollup-plugin-polyfill-node` to solve it? 🤔

---

Tagging @connorjclark @giuseppeg @ice1000 @imranbarbhuiya @i7eo @matikucharski @p-m-p as you all were interested in my first PR

Closes #18 for real now

### CODE REVIEW

**Comment by remorses** [comment]
The problem is that to use those polyfill you have to reimplement this resolver: https://github.com/FredKSchott/rollup-plugin-polyfill-node/blob/main/src/index.ts#L40

I am not really a rollup expert so i don't know how to translate it to esbuild 1 to 1

That's because the polyfills are importing code from those paths

**Comment by MichaelDeBoey** [comment]
> to use those polyfill you have to reimplement this resolver: https://github.com/FredKSchott/rollup-plugin-polyfill-node/blob/main/src/index.ts#L40

> I am not really a rollup expert so i don't know how to translate it to esbuild 1 to 1

@FredKSchott could you maybe point us into the right direction?

@remorses Can you think of any other solution to fix it? Maybe we shouldn't use `rollup-plugin-polyfill-node` but have the polyfills in another way available?

**Comment by p-m-p** [comment]
@MichaelDeBoey I presume you tagged me as I referenced this from my [issue](https://github.com/remix-run/remix/pull/4299) on the Remix repo.

I did look at your PR here when I raised that issue and think if you add another `onLoad` in the setup to namespace the modules prefixed with `\0polyfill-node.` and resolve them like is done here https://github.com/FredKSchott/rollup-plugin-polyfill-node/blob/main/src/index.ts#L75 it could probably work with some tweaking. Not all of the modules are in the modules map, some exist only in the exports of the polyfills file.

Probably not a helpful observation at this point but I do think it would be more beneficial to extract the polyfills properly into an esbuild plugin that is maintained in the Remix org.

**Comment by p-m-p** [comment]
This appears to work https://github.com/p-m-p/esbuild-plugins/commit/7edec138f0b2151baa7383164ffbd9a449a46dd5 but needs some testing and tidy up.

I can do later today if we think is a good solution, apologies for the whitespace changes.

**Comment by MichaelDeBoey** [comment]
@remorses I included @p-m-p's suggestions & test from #32, so I think this one's good to be merged in?
The added test is proving that internal `polyfill-node.*` imports (which come from `rollup-plugin-polyfill-node`) are resolved properly

**Comment by remorses** [comment]
Try using this plugin instead https://github.com/cyco130/esbuild-plugin-polyfill-node

This PR doesn't work

**Comment by MichaelDeBoey** [comment]
@remorses All tests are passing, so it should work now I guess?

Can you point me to what is still failing?
I'm happy to update this PR

**Comment by remorses** [comment]
Just use the plugin i linked above, that polyfill library isn't really maintained too, the plugin i linked instead uses an actively maintained polyfill (jspm)

**Pull request closed without merging**
